# Generated by Django 3.2.14 on 2024-10-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_categorykeyword_rejectedkeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorykeyword',
            name='category',
        ),
    ]
