# Generated by Django 5.1.2 on 2024-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_schedulesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stop_selenium',
            field=models.BooleanField(default=False),
        ),
    ]
