# Generated by Django 3.2.14 on 2024-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_schedulesettings_chrome_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=255)),
            ],
        ),
    ]
